### ISSUE TITLE
Finish baboba [1.5pt]

### ISSUE THREAD

**Issue by nilssonemma** [intergiro/cli#57]
## Tasks
- [x] Move worker-baboba to new cloudflare-account & update baboba urls in workers [0.5pt]
- [x] Finish ~settlement test in CLI~ [PR](https://github.com/intergiro/cli/pull/54) and create triggers for it in upcheck [0.5pt]
- [x] Set up demo- and test-merchants using baboba [0.5pt]

## Notes
- Finish settlement test in cli
- Make trigger work in worker-settlement
- Set up demo- and test-merchants using baboba

Set up new account on cloudflare to make testing easier!

## Documentation 
No.
